**Python para Dados - Atividade de Fixação Pandas**

Utilizando o arquivo: carros.csv

In [8]:
import pandas as pd

**Dataframe e ordenação:**

1. Faça o upload do CSV carros.csv.
   
2. Printe seu head com 10 linhas.

In [7]:
df = pd.read_csv('carros.csv')

df.head(10)

,Região,Estado,Quant Carros,Quant Carros Família com Filhos,População do Estado,Carros por habitante
0,Sul,Acre,4342,1034,23942.0,0.181355
1,Centro-Oeste,Alagoas,18991,3253,23431.0,0.810507
2,Sudeste,Amapá,6463,4152,7747.0,0.834258
3,Centro-Oeste,Amazonas,3180,2955,5189.0,0.612835
4,Centro-Oeste,Bahia,11288,2585,24118.0,0.468032
5,Nordeste,Ceará,10807,4943,40773.0,0.265053
6,Sudeste,Distrito Federal,5786,4459,6899.0,0.838672
7,Sudeste,Espírito Santo,5494,4073,6267.0,0.876655
8,Sudeste,Goiás,24412,2021,36551.0,0.667889
9,Centro-Oeste,Maranhão,8472,4461,16394.0,0.516774

3. Agora printe as colunas e index do dataframe.

In [10]:
df.columns

Index(['Região', 'Estado', 'Quant Carros', 'Quant Carros Família com Filhos',
       'População do Estado', 'Carros por habitante'],
      dtype='object')

In [11]:
df.index

RangeIndex(start=0, stop=27, step=1)

4. Faça um sort decrescente no dataframe pelo estado com maior quantidade de carros.

In [26]:
df.sort_values('Quant Carros', ascending=False)
df_estado_carros = df[['Estado', "Quant Carros"]]
df_estado_carros

                 Estado  Quant Carros
0                  Acre          4342
1               Alagoas         18991
2                 Amapá          6463
3              Amazonas          3180
4                 Bahia         11288
5                 Ceará         10807
6      Distrito Federal          5786
7        Espírito Santo          5494
8                 Goiás         24412
9              Maranhão          8472
10          Mato Grosso          4868
11   Mato Grosso do Sul          5683
12         Minas Gerais         17291
13                 Pará         22387
14              Paraíba         10666
15               Paraná          6036
16           Pernambuco         10533
17                Piauí          7912
18       Rio de Janeiro         33848
19  Rio Grande do Norte          6396
20    Rio Grande do Sul          2241
21             Rondônia         23113
22              Roraima          3561
23       Santa Catarina          9466
24            São Paulo          6317
25              Sergipe         22307
26            Tocantins         17144

5. Descubra qual a proporção de carro para a população de cada estado e insira em uma nova coluna.

In [24]:
proporcao = df['Quant Carros']/df['População do Estado']
df['Carros por habitante'] = proporcao
df.head()

,Região,Estado,Quant Carros,Quant Carros Família com Filhos,População do Estado,Carros por habitante
0,Sul,Acre,4342,1034,23942.0,0.181355
1,Centro-Oeste,Alagoas,18991,3253,23431.0,0.810507
2,Sudeste,Amapá,6463,4152,7747.0,0.834258
3,Centro-Oeste,Amazonas,3180,2955,5189.0,0.612835
4,Centro-Oeste,Bahia,11288,2585,24118.0,0.468032

6. Faça um dataframe com Estado e proporção de carro por habitante.

In [25]:
df_estado_hab = df[['Estado','Carros por habitante']]
df_estado_hab

                 Estado  Carros por habitante
0                  Acre              0.181355
1               Alagoas              0.810507
2                 Amapá              0.834258
3              Amazonas              0.612835
4                 Bahia              0.468032
5                 Ceará              0.265053
6      Distrito Federal              0.838672
7        Espírito Santo              0.876655
8                 Goiás              0.667889
9              Maranhão              0.516774
10          Mato Grosso              0.568957
11   Mato Grosso do Sul              0.639258
12         Minas Gerais              0.371004
13                 Pará              0.626385
14              Paraíba              0.546918
15               Paraná              0.225417
16           Pernambuco              0.674026
17                Piauí              0.573666
18       Rio de Janeiro              0.700453
19  Rio Grande do Norte              0.133192
20    Rio Grande do Sul              0.166828
21             Rondônia              0.481511
22              Roraima              0.222340
23       Santa Catarina              0.327577
24            São Paulo              0.829874
25              Sergipe              0.783169
26            Tocantins              0.773681

**Agregação de dados:**

7. Qual a média de idade por região?

8. Qual é a porcentagem de pessoas com deficiência?

9. Quantas pessoas são do estado do Piauí?

Utilizando o arquivo: concurso.csv

**Indexação e fatiamento:**

Temos como base inscrições em um concurso público, utilizando indexação retorne:

10. Quantas pessoas são do estado do Piauí?

11. Quantas do ES são do sexo feminino?