# **Desafio Python Pandas | Bootcamp Data Analytics 2024**

# Squad Sônia Guimarães

- desafio 1 - Maria e Ana
- desafio 2 - Leticia e Eliane
- desafio 3 - Suelen e Prisciele
- desafio 4 - Karine
- desafio 5 - Cedma e Natalia

## **Desafio 5: Forbes (Natalia e Cedma)**

**Definição do problema:** Você está trabalhando em um jornal e o
editor quer que você responda as seguintes questões:
1. Qual a empresa mais valiosa da lista da Forbes 2000?
2. Construa uma tabela com as TOP 10 empresas mais lucrativas da
lista.
3. Qual a média de valores de empresa das cinco categorias mais
valiosas?

**Código do dataset:** Forbes2000

**Dicas:**
- Método .max()
- Método nlargest()
- Método .groupby()

In [ ]:
# instalar a biblioteca para importação dos dados
!pip install pydataset
from pydataset import data

In [ ]:
# Carregar o dataset Forbes2000
forbes2000 = data('Forbes2000')

In [ ]:
# Visualizar o conjunto de dados
forbes2000.head()

   rank                 name         country  ... profits   assets  marketvalue
1     1            Citigroup   United States  ...   17.85  1264.03       255.30
2     2     General Electric   United States  ...   15.59   626.93       328.54
3     3  American Intl Group   United States  ...    6.46   647.66       194.87
4     4           ExxonMobil   United States  ...   20.96   166.99       277.02
5     5                   BP  United Kingdom  ...   10.27   177.57       173.54

[5 rows x 8 columns]

In [ ]:
# Qual a empresa mais valiosa da lista da Forbes 2000?
empresa_mais_valiosa = forbes2000.loc[forbes2000['marketvalue'].idxmax()]

print("Empresa mais valiosa:")
print(empresa_mais_valiosa[['name', 'marketvalue']])

Empresa mais valiosa:
name           General Electric
marketvalue              328.54
Name: 2, dtype: object

In [ ]:
# Construir uma tabela com as TOP 10 empresas mais lucrativas da lista
top_10_lucrativas = forbes2000.nlargest(10, 'profits')[['name', 'profits']]
print("\nTOP 10 empresas mais lucrativas:")
print(top_10_lucrativas)

TOP 10 empresas mais lucrativas:
                name  profits
4         ExxonMobil    20.96
1          Citigroup    17.85
2   General Electric    15.59
6    Bank of America    10.81
5                 BP    10.27
20       Freddie Mac    10.09
22      Altria Group     9.20
10   Wal-Mart Stores     9.05
31         Microsoft     8.88
17             Total     8.84

In [ ]:
# Qual a média de valores de empresa das cinco categorias mais valiosas?
top_categorias_valiosas = forbes2000.groupby('category')['marketvalue'].mean().nlargest(5)
print("\nMédia de valores de empresa das cinco categorias mais valiosas:")
print(top_categorias_valiosas)

Média de valores de empresa das cinco categorias mais valiosas:
category
Drugs & biotechnology          39.200000
Conglomerates                  25.874194
Semiconductors                 23.911538
Software & services            22.613226
Telecommunications services    21.857015
Name: marketvalue, dtype: float64